global:
  scrape_interval: 15s
  # VictoriaMetrics 싱글 노드는 규칙 평가를 직접 하지 않으므로 evaluation_interval은 제외합니다.

#  external_labels:
#    monitor: "my-project"

scrape_configs:
  # VictoriaMetrics 자체 메트릭 수집
  - job_name: "victoriametrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8428"]

  # 호스트 OS 리소스 수집 (node_exporter)
  - job_name: "node_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["server.local:9100"]

  # Java 애플리케이션 수집 (jmx_exporter)
  - job_name: "jmx_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["server.local:7071"]

  # Graphite 데이터 수집 (출력 포트인 9108 사용)
  - job_name: "graphite_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["server.local:9108"]

  # AWS CloudWatch 연동 수집
  - job_name: "cloudwatch_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["server.local:9106"]

  # Hadoop YARN 수집 (Python 버전)
  - job_name: "yarn-python-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["server.local:9459"]

  # Hadoop YARN 수집 (Prometheus 버전)
  - job_name: "yarn-prometheus-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["server.local:9113"]
