global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: "수집된 모든 데이터에 추가될 레이블"

#     A scrape configuration containing exactly one endpoint to scrape:
#     Here it's Prometheus itself.
scrape_configs:
  # 모니터링 시스템 자체의 상태를 수집
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  #  호스트 OS의 리소스(CPU, 메모리, 디스크 등) 상태를 수집
  - job_name: "node_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9100"]

  # Java 애플리케이션(JVM)의 내부 상태(Heap, GC 등)를 수집
  - job_name: "jmx_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:7071"]

  # Graphite 프로토콜로 들어오는 데이터를 수집
  - job_name: "graphite_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9108"]

  # AWS CloudWatch 메트릭을 연동하여 수집
  - job_name: "cloudwatch_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9106"]

  # monitoring/yarn-exporter/yarn_exporter.py
  - job_name: "yarn-python-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9459"]

  # https://github.com/PBWebMedia/yarn-prometheus-exporter
  - job_name: "yarn-prometheus-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9113"]
