services:
  kafka-broker:
    image: confluentinc/cp-kafka:8.0.0
    container_name: kafka-broker
    restart: always
    hostname: broker
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:39092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: BROKER://broker:29092,CONTROLLER://broker:39092,EXTERNAL://broker:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LOG4J_LOGGERS: org.apache.kafka.image.loader.MetadataLoader=WARN
      KAFKA_HEAP_OPTS: -Xms512m -Xmx512m
      KAFKA_MAX_MESSAGE_BYTES: "5242880"
      KAFKA_MESSAGE_MAX_BYTES: "5242880"
      KAFKA_NODE_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_PROCESS_ROLES: controller, broker
      KAFKA_ZOOKEEPER_CONNECT: null
    command:
      - /bin/bash
      - -c
      - |
        # Generate KRaft clusterID
        file_path="/var/lib/kafka/data/clusterID"

        if [ ! -f "$$file_path" ]; then
           /bin/kafka-storage random-uuid > $$file_path
           echo "Cluster id has been created..."
           # KRaft required step: Format the storage directory with a new cluster ID
           kafka-storage format --ignore-formatted -t $$(cat "$$file_path") -c /etc/kafka/kafka.properties
        fi

        export CLUSTER_ID=$$(cat "$$file_path")
        echo "CLUSTER_ID=$$CLUSTER_ID"

        /etc/confluent/docker/run
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z broker $${DATAHUB_KAFKA_BROKER_PORT:-9092}
      timeout: 5s
      interval: 1s
      retries: 5
      start_period: 1m0s
    networks:
      default: null
    ports:
      - 9092:9092
    volumes:
      - broker-data:/var/lib/kafka/data

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: datahub
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: datahub
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
      interval: 2s
      retries: 5
      start_period: 20s
    networks:
      default: null
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:2.17.0
    container_name: opensearch
    restart: always
    hostname: search
    environment:
      DISABLE_SECURITY_PLUGIN: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
      OPENSEARCH_JAVA_OPTS: -Xms768m -Xmx1024m -Dlog4j2.formatMsgNoLookups=true
      discovery.type: single-node
    deploy:
      resources:
        limits:
          memory: "2147483648"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -sS --fail http://search:$${DATAHUB_ELASTIC_PORT:-9200}/_cluster/health?wait_for_status=yellow&timeout=0s
      timeout: 15s
      interval: 5s
      retries: 10
      start_period: 1m0s
    networks:
      default: null
    ports:
      - 9200:9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  mysql-setup:
    image: acryldata/datahub-mysql-setup:${DATAHUB_VERSION}
    container_name: mysql-setup
    restart: on-failure
    hostname: mysql-setup
    depends_on:
      mysql:
        condition: service_healthy
        required: true
    environment:
      CDC_MCL_PROCESSING_ENABLED: "false"
      CDC_PASSWORD: datahub_cdc
      CDC_USER: datahub_cdc
      DATAHUB_DB_NAME: datahub
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: datahub
    networks:
      default: null
    labels:
      datahub_setup_job: "true"

  opensearch-setup:
    image: acryldata/datahub-elasticsearch-setup:${DATAHUB_VERSION}
    container_name: opensearch-setup
    restart: on-failure
    hostname: opensearch-setup
    depends_on:
      opensearch:
        condition: service_healthy
        required: true
    environment:
      ELASTICSEARCH_HOST: search
      ELASTICSEARCH_PORT: "9200"
      ELASTICSEARCH_PROTOCOL: http
      ELASTICSEARCH_USE_SSL: "false"
      USE_AWS_ELASTICSEARCH: "true"
    command:
      - /bin/sh
      - -c
      - /create-indices.sh
    networks:
      default: null
    labels:
      datahub_setup_job: "true"

  system-update:
    image: acryldata/datahub-upgrade:${DATAHUB_VERSION}
    container_name: system-update
    restart: on-failure
    hostname: system-update
    depends_on:
      mysql:
        condition: service_healthy
        required: true
      mysql-setup:
        condition: service_completed_successfully
        required: true
      opensearch:
        condition: service_healthy
        required: true
      opensearch-setup:
        condition: service_completed_successfully
        required: true
    environment:
      BACKFILL_BROWSE_PATHS_V2: "true"
      DATAHUB_BASE_PATH: /
      DATAHUB_GMS_BASE_PATH: /
      DATAHUB_GMS_HOST: datahub-gms
      DATAHUB_GMS_PORT: "8080"
      DATAHUB_PRECREATE_TOPICS: "true"
      EBEAN_DATASOURCE_DRIVER: com.mysql.jdbc.Driver
      EBEAN_DATASOURCE_HOST: mysql:3306
      EBEAN_DATASOURCE_PASSWORD: datahub
      EBEAN_DATASOURCE_URL: jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
      EBEAN_DATASOURCE_USERNAME: datahub
      ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES: "false"
      ELASTICSEARCH_HOST: opensearch
      ELASTICSEARCH_IMPLEMENTATION: opensearch
      ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX: "true"
      ELASTICSEARCH_INDEX_BUILDER_REFRESH_INTERVAL_SECONDS: "3"
      ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX: "true"
      ELASTICSEARCH_PORT: "9200"
      ELASTICSEARCH_PROTOCOL: http
      ELASTICSEARCH_USE_SSL: "false"
      ENTITY_REGISTRY_CONFIG_PATH: /datahub/datahub-gms/resources/entity-registry.yml
      ENTITY_VERSIONING_ENABLED: "true"
      GRAPH_SERVICE_IMPL: elasticsearch
      KAFKA_BOOTSTRAP_SERVER: broker:29092
      KAFKA_SCHEMAREGISTRY_URL: http://datahub-gms:8080/schema-registry/api/
      NEO4J_HOST: http://neo4j:7474
      NEO4J_PASSWORD: datahub
      NEO4J_URI: bolt://neo4j
      NEO4J_USERNAME: neo4j
      REPROCESS_DEFAULT_BROWSE_PATHS_V2: "false"
      SCHEMA_REGISTRY_SYSTEM_UPDATE: "true"
      SCHEMA_REGISTRY_TYPE: INTERNAL
      SPRING_KAFKA_PROPERTIES_AUTO_REGISTER_SCHEMAS: "true"
      SPRING_KAFKA_PROPERTIES_USE_LATEST_VERSION: "true"
      USE_CONFLUENT_SCHEMA_REGISTRY: "false"
    command:
      - -u
      - SystemUpdate
    networks:
      default: null
    volumes:
      - .datahub/plugins:/etc/datahub/plugins
    labels:
      datahub_setup_job: "true"

  datahub-frontend-react:
    image: acryldata/datahub-frontend-react:${DATAHUB_VERSION}
    container_name: datahub-frontend-react
    restart: always
    hostname: datahub-frontend-react
    depends_on:
      system-update:
        condition: service_completed_successfully
        required: true
    environment:
      DATAHUB_APP_VERSION: ${DATAHUB_VERSION}
      DATAHUB_BASE_PATH: /
      DATAHUB_GMS_BASE_PATH: /
      DATAHUB_GMS_HOST: datahub-gms
      DATAHUB_GMS_PORT: "8080"
      DATAHUB_PLAY_MEM_BUFFER_SIZE: 10MB
      DATAHUB_SECRET: ${DATAHUB_SECRET}
      DATAHUB_TRACKING_TOPIC: DataHubUsageEvent_v1
      ELASTIC_CLIENT_HOST: elasticsearch
      ELASTIC_CLIENT_PORT: "9200"
      JAVA_OPTS:
        -Xms512m -Xmx512m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf
        -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null
      KAFKA_BOOTSTRAP_SERVER: broker:29092
      PLAY_HTTP_CONTEXT: /
      THEME_V2_DEFAULT: "true"
      METADATA_SERVICE_AUTH_ENABLED: "true"
      AUTH_JAAS_ENABLED: "true"
    networks:
      default: null
    ports:
      - 9002:9002
    volumes:
      - .datahub/plugins:/etc/datahub/plugins
      - ./auth/jaas.conf:/datahub-frontend/conf/jaas.conf

  datahub-gms:
    image: acryldata/datahub-gms:${DATAHUB_VERSION}
    container_name: datahub-gms
    restart: always
    hostname: datahub-gms
    depends_on:
      system-update:
        condition: service_completed_successfully
        required: true
    environment:
      ALTERNATE_MCP_VALIDATION: "true"
      DATAHUB_BASE_PATH: /
      DATAHUB_GMS_BASE_PATH: /
      DATAHUB_SERVER_TYPE: quickstart
      DATAHUB_TELEMETRY_ENABLED: "false"
      DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID: generic-duhe-consumer-job-client-gms
      EBEAN_DATASOURCE_DRIVER: com.mysql.jdbc.Driver
      EBEAN_DATASOURCE_HOST: mysql:3306
      EBEAN_DATASOURCE_PASSWORD: datahub
      EBEAN_DATASOURCE_URL: jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
      EBEAN_DATASOURCE_USERNAME: datahub
      ELASTICSEARCH_HOST: search
      ELASTICSEARCH_IMPLEMENTATION: opensearch
      ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX: "true"
      ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX: "true"
      ELASTICSEARCH_LIMIT_RESULTS_STRICT: "true"
      ELASTICSEARCH_PORT: "9200"
      ELASTICSEARCH_PROTOCOL: http
      ELASTICSEARCH_USE_SSL: "false"
      ENTITY_REGISTRY_CONFIG_PATH: /datahub/datahub-gms/resources/entity-registry.yml
      ENTITY_SERVICE_ENABLE_RETENTION: "true"
      ENTITY_VERSIONING_ENABLED: "true"
      ES_BULK_REFRESH_POLICY: WAIT_UNTIL
      GRAPH_SERVICE_DIFF_MODE_ENABLED: "true"
      GRAPH_SERVICE_IMPL: elasticsearch
      JAVA_OPTS: -Xms1g -Xmx1g
      KAFKA_BOOTSTRAP_SERVER: broker:29092
      KAFKA_SCHEMAREGISTRY_URL: http://datahub-gms:8080/schema-registry/api/
      MAE_CONSUMER_ENABLED: "true"
      MCE_CONSUMER_ENABLED: "true"
      METADATA_SERVICE_AUTH_ENABLED: "false"
      NEO4J_HOST: http://neo4j:7474
      NEO4J_PASSWORD: datahub
      NEO4J_URI: bolt://neo4j
      NEO4J_USERNAME: neo4j
      PE_CONSUMER_ENABLED: "true"
      SCHEMA_REGISTRY_TYPE: INTERNAL
      SEARCH_BAR_API_VARIANT: SEARCH_ACROSS_ENTITIES
      SHOW_HAS_SIBLINGS_FILTER: "true"
      SHOW_HOME_PAGE_REDESIGN: "true"
      SHOW_INGESTION_PAGE_REDESIGN: "true"
      SHOW_SEARCH_BAR_AUTOCOMPLETE_REDESIGN: "true"
      STRICT_URN_VALIDATION_ENABLED: "true"
      THEME_V2_DEFAULT: "true"
      UI_INGESTION_ENABLED: "true"
      UI_INGESTION_DEFAULT_CLI_VERSION: ${UI_INGESTION_DEFAULT_CLI_VERSION}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -sS --fail http://datahub-gms:8080/health
      timeout: 5s
      interval: 1s
      retries: 3
      start_period: 1m30s
    networks:
      default: null
    ports:
      - 8080:8080
    volumes:
      - .datahub/plugins:/etc/datahub/plugins
      - .datahub/search:/etc/datahub/search
    labels:
      io.datahubproject.datahub.component: gms

  datahub-actions:
    image: acryldata/datahub-actions:${DATAHUB_VERSION}-slim
    build:
      context: .
      dockerfile: actions.Dockerfile
    container_name: datahub-actions
    restart: always
    hostname: actions
    depends_on:
      datahub-gms:
        condition: service_healthy
        required: true
    environment:
      ACTIONS_CONFIG: ""
      ACTIONS_EXTRA_PACKAGES: ""
      DATAHUB_GMS_HOST: datahub-gms
      DATAHUB_GMS_PORT: "8080"
      DATAHUB_GMS_PROTOCOL: http
      DATAHUB_SYSTEM_CLIENT_ID: __datahub_system
      DATAHUB_SYSTEM_CLIENT_SECRET: ${DATAHUB_SYSTEM_CLIENT_SECRET}
      ELASTICSEARCH_HOST: search
      ELASTICSEARCH_PORT: "9200"
      ELASTICSEARCH_PROTOCOL: http
      ELASTICSEARCH_USE_SSL: "false"
      KAFKA_BOOTSTRAP_SERVER: broker:29092
      KAFKA_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      METADATA_AUDIT_EVENT_NAME: MetadataAuditEvent_v4
      METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME: MetadataChangeLog_Versioned_v1
      SCHEMA_REGISTRY_URL: http://datahub-gms:8080/schema-registry/api/
    networks:
      default: null

networks:
  default:
    driver: bridge
    name: service-network

volumes:
  mysql-data:
    driver: local
  broker-data:
    driver: local
  opensearch-data:
    driver: local
