services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
    command: |
      /bin/sh -c "
      envsubst '$$SERVER_NAME' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf \
      envsubst '$$SERVER_NAME' < /etc/nginx/templates/minio.conf.template > /etc/nginx/conf.d/minio.conf \
      envsubst '$$SERVER_NAME' < /etc/nginx/templates/polaris.conf.template > /etc/nginx/conf.d/polaris.conf \
      envsubst '$$SERVER_NAME' < /etc/nginx/templates/trino.conf.template > /etc/nginx/conf.d/trino.conf \
      while :; do \
        sleep 6h & wait $${!}; \
        nginx -s reload; \
      done & \
      nginx -g 'daemon off;'
      "
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/template:/etc/nginx/template
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

networks:
  default:
    driver: bridge
    name: service-network
