services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: always
    command: -conf /Corefile
    networks:
      - default
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./data/Corefile:/Corefile

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
    command: |
      /bin/sh -c "
      envsubst '$$DOMAIN' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf \
      envsubst '$$DOMAIN' < /etc/nginx/template/minio.conf.template > /etc/nginx/conf.d/minio.conf \
      envsubst '$$DOMAIN' < /etc/nginx/template/polaris.conf.template > /etc/nginx/conf.d/polaris.conf \
      envsubst '$$DOMAIN' < /etc/nginx/template/trino.conf.template > /etc/nginx/conf.d/trino.conf \
      envsubst '$$DOMAIN' < /etc/nginx/template/airflow.conf.template > /etc/nginx/conf.d/airflow.conf \
      envsubst '$$DOMAIN' < /etc/nginx/template/kafka-ui.conf.template > /etc/nginx/conf.d/kafka-ui.conf \
      while :; do \
        sleep 6h & wait $${!}; \
        nginx -s reload; \
      done & \
      nginx -g 'daemon off;'
      "
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/template:/etc/nginx/template
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    depends_on:
      coredns:
        condition: service_started

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

networks:
  default:
    driver: bridge
    name: service-network
