services:
  controller:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: controller
    hostname: controller
    environment:
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller:9093
      KAFKA_LISTENERS: CONTROLLER://controller:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -z controller 9093 || exit 1"]
      interval: 5s
      retries: 5
    networks:
      - default
    ports:
      - 9093:9093
    volumes:
      - ./secrets/controller.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks
      - ./secrets/truststore.jks:/etc/kafka/secrets/truststore.jks

  broker:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: broker
    hostname: broker
    restart: always
    environment:
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_NODE_ID: 100
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker:19092,HOST://localhost:9092
      KAFKA_LISTENERS: BROKER://:19092,HOST://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL,BROKER:SSL,HOST:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      # Broker 리스너 간 SASL_SSL 사용 시,
      # KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LISTENER_NAME_HOST_SSL_CLIENT_AUTH: none # External Access to Kafka Broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    depends_on:
      controller:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z broker 9092 || exit 1"]
      interval: 5s
      retries: 5
    networks:
      - default
    ports:
      - 9092:9092
    volumes:
      - ./jaas/kafka.jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./secrets/broker.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks
      - ./secrets/truststore.jks:/etc/kafka/secrets/truststore.jks

  init-scram:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: init-scram
    depends_on:
      broker:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/usr/bin/setup-scram.sh"]
    networks:
      - default
    volumes:
      - ./setup-scram.sh:/usr/bin/setup-scram.sh
      - ./secrets/broker.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks
      - ./secrets/truststore.jks:/etc/kafka/secrets/truststore.jks

  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
    container_name: schema-registry
    hostname: schema-registry
    restart: always
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      # SSL 사용 시,
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SSL://broker:19092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: changeit
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: changeit
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: changeit

      # SASL_SSL 사용 시,
      # SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SASL_SSL://broker:9092
      # SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
      # SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: SCRAM-SHA-256
      # SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="schemaregistry" password="schemaregistry";
      # SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      # SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: changeit
    depends_on:
      init-scram:
        condition: service_completed_successfully
        required: true
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://schema-registry:8081/subjects"]
      interval: 5s
      retries: 3
    networks:
      - default
    ports:
      - 8081:8081
    volumes:
      - ./secrets/broker.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks
      - ./secrets/truststore.jks:/etc/kafka/secrets/truststore.jks

networks:
  default:
    driver: bridge
    name: service-network
