database:
  mysql:
    host: "mysql.svc.internal"
    port: 3306
    user: "root"
    password: "mysql"
    database: "store"
    autocommit: false
  sqlserver:
    host: "sqlserver.svc.internal"
    port: 1433
    user: "SA"
    password: "foqaktmxj01!"
    database: "store"
    autocommit: false

generate:
  duration: 1 # duration in seconds
  transactions: 20 # I,U,D transaction per seconds
  insert_rate: 0.60 # insert rate
  update_rate: 0.30 # update rate
  delete_rate: 0.10 # delete rate
  seed: 42

tables:
  - "tb_lower"
  - "TB_UPPER"
  - "TB_COMPOSITE_KEY"
