global:
  scrape_interval: 30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: "my-project"

rule_files:
  - "alert.rules"
  - "first.rules"
  - "second.rules"

    #alert
    #alerting:
    #  alertmanagers:
    #   - scheme: http
    #    static_configs:
    #      - targets#:
    #       - "alertmanager:9093"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "jmx_exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:7071"]

  - job_name: "graphite_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9109"]

  - job_name: "cloudwatch_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9106"]

  # monitoring/yarn-exporter/yarn_exporter.py
  - job_name: "yarn-python-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9459"]

  # https://github.com/PBWebMedia/yarn-prometheus-exporter
  - job_name: "yarn-prometheus-exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9113"]
